PluginTest.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace PluginTest.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

PluginTest.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace PluginTest.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

PluginTest.Web/Controllers/AboutController.cs
using System.Web.Mvc;

namespace PluginTest.Web.Controllers
{
    public class AboutController : PluginTestControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

PluginTest.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace PluginTest.Web.Controllers
{
    public class HomeController : PluginTestControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

PluginTest.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Threading;
using PluginTest.Web.Models.Layout;

namespace PluginTest.Web.Controllers
{
    public class LayoutController : PluginTestControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILocalizationManager _localizationManager;

        public LayoutController(IUserNavigationManager userNavigationManager, ILocalizationManager localizationManager)
        {
            _userNavigationManager = userNavigationManager;
            _localizationManager = localizationManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.UserId)),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _localizationManager.CurrentLanguage,
                            Languages = _localizationManager.GetAllLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }
    }
}

PluginTest.Web/Views/About/Index.cshtml
@{
    ViewBag.ActiveMenu = "About"; //The menu item will be active for this page.
}
<div>
    <h1><img src="~/images/abp-logo.png" style="padding-right: 10px;" />@string.Format(L("AboutFormat"), "ASP.NET Boilerplate")</h1>
    <p>@Html.Raw(L("About_AspNetBoilerplateDescription"))</p>
    <p>@L("ForMoreInformation"): <a href="http://www.aspnetboilerplate.com"><strong>aspnetboilerplate.com</strong></a>.</p>
</div>

PluginTest.Web/Views/Home/Index.cshtml
@{
    ViewBag.ActiveMenu = "Home"; //The menu item will be active for this page.
}
<div>
    <h1>@L("WellcomeMessage")!</h1>
    <p class="lead">@L("Home_ThisIsATemplate")</p>
    <div class="row">
        <div class="col-md-4">
            <h3>ASP.NET MVC</h3>
            <p>
                @L("Home_AspNetDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://asp.net/mvc">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>ASP.NET Boilerplate</h3>
            <p>
                @L("Home_AspNetBoilerplateDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://aspnetboilerplate.com">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>@L("Others")</h3>
            <p>
                @L("Home_OtherTools")
            </p>
        </div>
    </div>
</div>

PluginTest.Web/Views/Layout/_LanguageSelection.cshtml
@model PluginTest.Web.Models.Layout.LanguageSelectionViewModel
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="@Model.CurrentLanguage.Icon"></i>
        <span>@Model.CurrentLanguage.DisplayName</span>
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        @foreach (var language in Model.Languages)
        {
            if (language.Name != Model.CurrentLanguage.Name)
            {
                <li><a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@(Request.Url)"><i class="@language.Icon"></i> @language.DisplayName</a></li>
            }
        }
    </ul>
</li>

PluginTest.Web/Views/Layout/_TopMenu.cshtml
@using Abp.Collections.Extensions
@model PluginTest.Web.Models.Layout.TopMenuViewModel
@foreach (var menuItem in Model.MainMenu.Items)
{
    <li class="@(Model.ActiveMenuItemName == menuItem.Name ? "active" : "")">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            <a href="@menuItem.Url">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
        }
        else
        {
            <a href="" data-toggle="dropdown">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var subMenuItem in menuItem.Items)
                {
                    <li>
                        <a href="@subMenuItem.Url">
                            @if (!string.IsNullOrWhiteSpace(subMenuItem.Icon))
                            {
                                <i class="@subMenuItem.Icon"></i>
                            }
                            @subMenuItem.DisplayName
                        </a>
                    </li>
                }
            </ul>
        }
    </li>
}

PluginTest.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>PluginTest</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name'); //Localizing momentjs
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll"></script>
    <script src="~/AbpScripts/GetScripts" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

PluginTest.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> PluginTest</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("LanguageSelection", "Layout")
            </ul>
        </div>
    </div>
</div>